# Generated by Django 4.1.4 on 2022-12-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussione',
            old_name='autore_duscussione',
            new_name='autore_discussione',
        ),
    ]
